version: "3.9"
services:
  coupon_db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      MSSQL_SA_PASSWORD: ${COUPON_DB_PASSWORD}
      MSSQL_PID: "Developer"
      MSSQL_USER: "SA"
      ACCEPT_EULA: "Y"
    ports:
      - "${COUPON_DB_PORT}:1433"
